# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/sim_racing_db
spring.datasource.username=postgres
spring.datasource.password=Gabriele.07
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080

# App name
spring.application.name=sim-racing-backend